[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"
  NODE_ENV = "16.11.0"
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/us/"
  conditions = {Country = ["US"]}
  status = 200
  force = true

[[redirects]]
  from = "/create"
  to = "/us/create"
  conditions = {Country = ["US"]}
  status = 200
  force = true

[[redirects]]
  from = "/lolly/*"
  to = "/popsicle/:splat"
  conditions = {Country = ["US"]}
  status = 302
  force = true

# resolve the "new" URL to a function
[[redirects]]
  from = "/new"
  to = "/.netlify/functions/newLolly"
  status = 200

# lolly page requests will be rendered and persisted on demand
[[redirects]]
  from = "/lolly/*"
  to = "/.netlify/functions/showLolly"
  status = 200

[[redirects]]
  from = "/popsicle/*"
  to = "/.netlify/functions/showLolly"
  status = 200


# Not found? This really is a 404
[[redirects]]
  from = "/*"
  to = "/melted/index.html"
  force = false
  status = 404

[[redirects]]
  from = "/*"
  to = "/us/melted/index.html"
  conditions = {Country = ["US"]}
  force = false
  status = 404

